import { Header, Footer } from '@fs-starter/layout';
import './global.css';

export const metadata = {
  title: 'Welcome to auth',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
