import { Header, Footer } from "@fs-starter/layout";
import { HeaderServer, FooterServer } from "@fs-starter/layout/server";
import "./global.css";

export const metadata = {
  title: "Welcome to auth",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header>
          <HeaderServer />
        </Header>
        {children}
        <Footer>
          <FooterServer />
        </Footer>
      </body>
    </html>
  );
}
